### ISSUE TITLE
Recursive defintions

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#1]
Your language currently does not support recursive defintions it seems. 

Both in let bindings and top level bindings, you need to add the binding to your environment before you evaluate the body of the let/function. 

Maybe something like this (names are debatable, also not typechecked or anything):

```
mindBoggling :: [Declaration] -> Env
mindBoggling ds = let e = addDecsToEnv' ds e in e

-- This function takes its own result as input, be careful about inspecting it
addDecsToEnv' :: [Declaration] -> Env -> Env
addDecsToEnv' [] _        = M.empty
addDecsToEnv' (d:ds) env  = uncurry M.insert (makeBinding d env) e'
  where
    e' = addDecsToEnv' ds env

makeBinding :: Declaration -> Env -> (Var,Value)
```

Note how this follows the pattern of delegating everything to Haskell: To implement recursion (self reference) we need a highly self-referential function.

**Comment by JonasDuregard** [comment]
Currently there is a small bug in interpret that prevents recursive definitions. I changed the base case of addDecsToEnv to M.empty and the defintion of e to addDecsToEnv e ds in interpret and it works splendidly. Here are some tests including an untested implementation of map. 

```
test1 = interpret ds >>= putStrLn . take 1000 . show where
  ds = [main]
  main = DFunc "main" [] body
  body = ECon "Cons" [(ELit (ILit 1)), EVar "main"]


test2 = interpret ds >>= putStrLn . take 1000 . show where
  cons = "Cons"  
  ds = [main,go,map]
  main = DFunc "main" [] body where
    body = EApp (EVar "go") (ELit (ILit 1))

  go = DFunc "go" ["x"] body where
    x = EVar "x"
    body = ECon cons [x, EVar "go" `EApp` (x `EAdd` x)]

  map = DFunc "map" [f,"xs0"] body where
    (f,x,xs) = ("f","x","xs")
    body = ECase (EVar "xs0") 
     [(cons,[x,xs],ECon cons [EVar f `EApp` EVar x,EVar "map" `EApp` EVar f `EApp` EVar xs])
     ,("Nil",[],ECon "Nil" [])
     ]
```

**Comment by MarieKlevedal** [comment]
this is implemented

**Comment by JonasDuregard** [comment]
It still needs to be fixed for let-bindings. Luckily this can be done by adding a single character (a ') to the current source (unless you also want to allow multiple let bindings, in which case you should reuse code for adding definitions.

**Comment by herrlax** [comment]
I believe this is fixed!
