### ISSUE TITLE
IO

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#10]
The FIO constructor of Value seems to just be a combination of VFun and VIO, it should be removed. 

The value of printF should be VFun $ (VString s) -> VIO (putStrLn s >> return unit)

Where unit is a value something like VConstr "()" [].

bind will have to be modified accordingly (it takes a VIO and a VFun, and produces a VIO that applies the result of the VIO to the function and extracts IO-action from the resulting VIO).

**Comment by herrlax** [comment]
@JonasDuregard By removing FIO and modifying bind accordingly we end up with VFun $ (VIO a1) -> VFun $ (VFun a2) -> VIO $ a1 >>= \s -> return (a2 s), but there are difficulties in extracting the IO-actions from this.

**Comment by JonasDuregard** [comment]
@herrlax 
(a2 s) is a Value. We know that if the program is type correct, it should be a VIO (since the "lolipop-type" of a2 must be (a -> IO b)) and all values of type IO x should be VIO. So what you need is a case on (a2 s) instead of just returning it. A helper function (runIO :: Value -> IO Value) could be used, that just extracts the IO action contained in a VIO (so: runIO (VIO m) = m) and gives an error for other types of values.

**Comment by JonasDuregard** [comment]
Why does run always produce a unit? That means bind will always produce a unit so its not type correct (it is now `IO a -> (a -> IO b) -> IO ())`. Maybe just remove the `>> return (VConstr "()" [])` bit?
