### ISSUE TITLE
built in functions

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#11]
I would suggest having some otherwise syntactically invalid prefix for the built in operators in the environment (e.g. "#Add" instead of "add". That way your interpreter does not break if i do (let add = 1 in add+add). 

Also, a nice trick could be to lookup ("#"+show op) in the interpreter instead of having a separate case for each operation that just maps operators to strings.

**Comment by herrlax** [comment]
commit message addressed wrong issue, should be #12

**Comment by JonasDuregard** [comment]
Now it is called Add, but that could be the name of a constructor? (And constructors are stored in the same environment?)

Also, I don't think print and such should have special names (because they should be usable). Only the operators need them because they are handled separately from ordinary functions.
