### ISSUE TITLE
Operators

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#12]
Currently, the interpreter for EOp appears to return the operator itself, but the AST is an _operator application_. It has two expressions that need to be applied to the operator. 

Also, why is there an EBind constructor? How is EBind Bind different from EBinOp Bind?

**Comment by herrlax** [comment]
closed in commit [42b7b3b](https://github.com/m0ar/lollipop/commit/42b7b3bdf418866264c8c51c1de1aa3931928cd4)
