### ISSUE TITLE
Tuples

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#14]
Keep in mind that a tuple is just a special constructor. So for instance a 3-tuple could be 
(,,) e1 e2 e3
where (,,) is a constructor of type a -> b -> c -> (a,b,c).
This can already be encoded in your expression type, in your patterns and in your value type without adding anything new. Just add a binding for "(,,)" in your start environment. 

If you want to have a more general way of dealing with tuples (of any size) you can add an ETuple [Exp] to your expression type, but for now you can just add a few tuple constructors to the start environment (maybe write a function that generates a given number of tuple constructors).

**Comment by MarieKlevedal** [comment]
This is implemented
