### ISSUE TITLE
Read eval print loop

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#17]
To play around a bit with your interpreter I wrote this little front end that glues the pieces of your program together and allows you to load files and run expressions (just like in ghci). Apparently Github does not allow me to attach files to these issues so I will just paste the code I used, feel free to use it as you wish.

Apparently GitHub does not allow attaching a .hs file, so I will just rename it .txt...
[Repl.hs.txt](https://github.com/m0ar/lollipop/files/177532/Repl.hs.txt)

An obvious todo is type checking, also it is a bit brittle, for instance a pattern match failure in evaluated code will crash the whole interpreter instead of just giving an error. Maybe there should be a VError constructor, or maybe eval should give Either String Value (but those changes would require some work).

**Comment by JonasDuregard** [comment]
Oh, you need to import System.IO and add `hFlush stdout`after `putStr $ file ++ ">"` for it to work when compiled.

**Comment by JonasDuregard** [comment]
Here is a program that the interpreter does not like so much. Apparently the conversion module does not yet support function application. 

function one : Int -> [Int] ;
one := \x -> 1 ;

function take : Int -> [a] -> [a] ;
take n (x:xs) := case n of 0 -> cons x (take (n-1) xs) ; 
                           _ -> nil ;
  ;
take n []    := nil ; -- There is no way to do empty lists :(

function map : atob -> [a] -> [b] ;
map f (x:xs) := cons (f x) (map f xs) ;
map f []     := nil ;

function naturals : [Int] ;
naturals := cons 0 (map (\x -> x+1) naturals) ;

function foldr : atobtob -> b -> [a] -> b ; 
foldr f b []     := b ;
foldr f b (x:xs) := f x (foldr f b xs) ;

-- Sum of first 100 naturals
function main : Int ;
main := foldr (\x -> \y -> (x+y)) 0 (take 100 naturals) ;

**Comment by herrlax** [comment]
This can be found in the repo
