### ISSUE TITLE
No way to write list expressions?

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#18]
It seems there is no way to write expressions such as [] and (x:xs), which makes writing list functions impossible.

**Comment by JonasDuregard** [comment]
Apparently, the problem with [] is that it's lexed as a single symbol, so it needs a space to work...

**Comment by m0ar** [comment]
@JonasDuregard Workaround for empty list expressions were added with 9a7cddc. Currently looking at implementing _cons_ but I'm getting shift/reduce-conflicts so I'll get back on that after the weekend.

**Comment by herrlax** [comment]
This works
