### ISSUE TITLE
Constructors and cases

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#2]
Two small issues: 
- You need to add constructors and constructor applications in your expressions (arguably replacing EList). One way to do it is to add | ECon ConID to Exp. Then you can store each constructor in your Env as a VFun that ends up producing a VCon when saturated. This means you use ordinary function application for constructor applications. It would mean you would have to add all constructors as functions to your initial environment, so you need to add data type declarations.  
- Maybe case expressions can have a default case (like _)? (Low priority)

**Comment by JonasDuregard** [comment]
For example list cons and nil would be encoded as:

```
VFun (\v1 -> VFun (\v2 -> VCon "Cons" [v1,v2]))
VCon "Nil" []
```

For starters you could just add those binding manually to your starting environment, delaying implementing data declarations. If you are really lazy you could even use the existing EVar constructor instead of a new ECon to use them.

**Comment by herrlax** [comment]
This is fixed
