### ISSUE TITLE
Bug in vConstructor

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#27]
I think vConstructor currently builds lists backwards compared to how you use them.

**Comment by MarieKlevedal** [comment]
It works fine the way it it

**Comment by JonasDuregard** [comment]
Right, my mistake.

It's a bit unfortunate to use ++ though, since it's linear complexity making the whole application quadratic. 

You could reverse the list in the base case, or use continuation passing (pass a ([Value] -> [Value]) around instead of [Value], start with id instead of [] and use ((v:) .) instead of (++ [v]) and in the base case apply the function to [].

**Comment by MarieKlevedal** [comment]
This is now implemented, but using (. (v:)) instead of ((v:) .) to build the list in the correct order.
