### ISSUE TITLE
Lazy evaluation not always working

### ISSUE THREAD

**Issue by MarieKlevedal** [m0ar/lollipop#29]
For example, lazy1 doesn't work, while lazy2 does.

lazy1 := first 5 infty
lazy2 := second infty 5

first x y := x
second x y := y

infty := 1 + infty

**Comment by JonasDuregard** [comment]
I was unable to replicate this bug. I tried this code and it seems to work:

```
function lazy1 : X;
lazy1 := first 5 infty;

function infty : X;
infty := 1 + infty;

function lazy2 : X;
lazy2 := second infty 5;

function first : X;
first x y := x;

function second : X;
second x y := y;
```

**Comment by herrlax** [comment]
It seems that this has magically been solved in an unknown commit.
