### ISSUE TITLE
List Comprehensions in AST

### ISSUE THREAD

**Issue by herrlax** [m0ar/lollipop#30]
Is it a good idea to represent list comprehensions as its own expression in the AST, having a main-expression forming the actual list and a list of constraints as: EListComp = Exp [Exp]. In this case it's difficult to clearly see where the "x <- xs" comes in.

**Comment by JonasDuregard** [comment]
I would not have list comprehensions in the core AST. They can be desugared into applications of filter, maps, binds and case expressions. But doing this desugaring is low priority, better to just leave them out for now. 

If it where in the AST it would be an expression and a [Either Exp (Pattern,Exp)] where the two alternatives are either a condition (Exp of type Bool) or a binding (p <- e).

**Comment by m0ar** [comment]
List comprehensions have been deprioritized.
