### ISSUE TITLE
Abstractions can only take one variable

### ISSUE THREAD

**Issue by m0ar** [m0ar/lollipop#32]
Should be a quick fix, but if we change the grammar we also need to change representations in the abstract syntax and handling in converter etc.

**Comment by JonasDuregard** [comment]
You can allow multiple variables in the surface syntax but have the converter change `\a b c -> e` into `\a -> \b -> \c -> e`.

Avoid changes to your core syntax as far as possible at this point.

You could also allow patterns in your surface syntax but that is low priority.
