### ISSUE TITLE
The dreaded undefined

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#34]
Currently you model undefined values as a special constructor.

This is bad because your interpreter will crash for things like (undefined 0) or (undefined + 1). Modifying your interpreter to expect this constructor everywhere is incredibly tedious. Maybe you should use Control.Exception to throw a special error? 
https://hackage.haskell.org/package/base-4.8.2.0/docs/Control-Exception.html

I would suggest defining a data type like so: 

```
data Error = Error String deriving (Show, Typeable)
instance Exception MyException
```

Now your repl can just catch this, print the error and proceed (and undefined would be `throw (Error "Undefined")`, but you can add other error messages including user defined ones (like the error function in haskell, challenge: add this to your start environment!).

**Comment by m0ar** [comment]
This is very reasonable. We will keep it for placeholder definition purposes but absolutely revise the usage of it as a error catching construct. Thank your for the input!
