### ISSUE TITLE
Unclear how to proceed with the test suite

### ISSUE THREAD

**Issue by m0ar** [m0ar/lollipop#35]
As of now, testing has been done by writing willie-nillie implementations in testProgram.lp and checking intuitive results. The perferred solutions would be something quick check-esque, but since our language doesn't have any sophisticated testing tools this is impossible. Could we argue that this testing is enough, and can we still call this a "test suite"?

**Comment by JonasDuregard** [comment]
Yes, unit tests are enough. 

But you could use QuickCheck as well, even without implementing it in lolipop by writing haskell properties about the behavior of eval etc. 

But testing compilers is notoriously difficult, because it is difficult to generate type correct programs.

**Comment by m0ar** [comment]
@JonasDuregard Aight. Then this is where we will draw the line :)
