### ISSUE TITLE
higher order impairment

### ISSUE THREAD

**Issue by Hsiang-Yu** [m0ar/lollipop#37]
Fix grammar so that is allows type declarations with functions as parameters that themselves take more than two parameters. For instance this is not possible at the moment:
(a -> b -> c) -> [a] -> [c]

**Comment by JonasDuregard** [comment]
Isn't this just because you require parenthesis everywhere? (So `(a -> (b -> c)) -> ([a] -> [c])` might work?)

Still, that should be fixed.

**Comment by Hsiang-Yu** [comment]
Fixed
