### ISSUE TITLE
grammarLet

### ISSUE THREAD

**Issue by MarieKlevedal** [m0ar/lollipop#5]
Är det en bra avgränsning att bara tillåta en tilldelning i en let-in?

**Comment by JonasDuregard** [comment]
Nej, det gör det svårt att definiera ömsesidigt rekursiva funktioner med let. (Men just nu fungerar inte rekursiva let-definitioner alls?)

**Comment by herrlax** [comment]
Let (utan "in") kommer väl kräva sequencing, vilket känns som något som är vettigt att avgränsa sig ifrån?

**Comment by m0ar** [comment]
After reprioritization single assignment let-in is now the current solution.
