### ISSUE TITLE
Minimizing the expression type

### ISSUE THREAD

**Issue by JonasDuregard** [m0ar/lollipop#7]
Here are some more construcors that I think should be removed or moved to some other data type:
EIf (convert to case), EWhere (remove or move to declaration level), EGuard (use case?), EPrint (just add a binding to start environment). Also either remove EAdd and EMult and just add bindings for them in the environment or replace them with EOp Exp Op Exp.

In the environment you could add for instance 
("i+", VFun ((VInt a) -> VFun ((VInt b) -> VInt (a + b))))
to implement integer addition. Print would be something like this with your current interface:
("print", VFun ((VString s) -> VIO s))
But VIO is not really how it should be (Maybe it should take IO () instead? Or IO Value?), and I really think you should remove VString and have a printChar function as primitive instead, and implement strings and print in your prelude instead of built into the interpreter. 

Also, should SimpleBool really exist? Are True and False not constructors?

Everything you remove from Exp will make your type checker and interpreter simpler.

**Comment by herrlax** [comment]
Everything in this issue has been resolved, except the removing VString-part
